    export const Products=[
    {id:0,
    img:process.env.PUBLIC_URL + '/mob1.jpeg',
    title:"google pixel",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:1,
    img:process.env.PUBLIC_URL + '/shirt1.jpg',
    title:"Smart shirtb for males",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:2,
    img:process.env.PUBLIC_URL + '/shirt2.jpg',
    title:"iPhone 11",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:3,
    title:"samsumg",
    img:process.env.PUBLIC_URL + '/mob1.jpeg',
    price:10,
    company:"verizone",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:4,
    img:process.env.PUBLIC_URL + '/cycleglass.jpeg',
    title:"Cycling Sunglasses Riding Bluetooth Earphone",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:5,
    img:process.env.PUBLIC_URL + '/shirt4.jpg',
    title:"T-Shirt red",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:6,
    img:process.env.PUBLIC_URL + '/mob2.jpg',
    title:"google pixel",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:7,
    img:process.env.PUBLIC_URL + '/glass.jpeg',
    title:"Sun Glasses ",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},{id:8,
    img:process.env.PUBLIC_URL + '/mob3.jpg',
    title:"Smart Watch",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:9,
    img:process.env.PUBLIC_URL + '/mob5.jpg',
    title:"google pixel",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:10,
    img:process.env.PUBLIC_URL + '/glass.jpeg',
    title:"Sun Glasses",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:11,
    img:process.env.PUBLIC_URL + '/iphoneconvert.jpeg',
    title:"iPhone 11",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:12,
    title:"samsumg",
    img:process.env.PUBLIC_URL + '/mob1.jpeg',
    price:10,
    company:"verizone",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:13,
    img:process.env.PUBLIC_URL + '/cycleglass.jpeg',
    title:"Cycling Earphone",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
},
{id:14,
    img:process.env.PUBLIC_URL + '/watch.jpeg',
    title:"Smart Watch Ios",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
}
]



export const Detail=
{id:0,
    img:process.env.PUBLIC_URL + '/null.jpeg',
    title:"Sprayer Water",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
}
